class Quote
  attr_accessor :quote_hash, :category
  attr_reader :quote 
    
    def initialize(category)
      @category=category
      @quote_hash = {

        :the_economy => ["Free trade is terrible. Free trade can be wonderful if you have smart people. But we have stupid people.", "The American Dream is dead", "I will be the greatest jobs president that God ever created", "We need money. We're dying"],
        :foreign_relations => ["When was the last time anybody saw us beating, let's say, China in a trade deal? They kill us. I beat China all the time. All the time.", "When Mexico sends its people, they're not sending the best. They're not sending you, they're sending people that have lots of problems and they're bringing those problems with us. They’re bringing drugs. They’re bringing crime. They’re rapists. ... And some, I assume, are good people.","When was the last time you saw a Chevrolet in Tokyo?","I will build a great wall — and nobody builds walls better than me, believe me —and I’ll build them very inexpensively. I will build a great, great wall on our southern border, and I will make Mexico pay for that wall.", "What can be simpler or more accurately stated? The Mexican Government is forcing their most unwanted people into the United States. They are, in many cases, criminals, drug dealers, rapists, etc.", "Listen you m—–f——, we’re going to tax you 25 percent! (on exporting goods to China)"],
    :race_relations => ["The U.S. will invite El Chapo, the Mexican drug lord who just escaped prison, to become a U.S. citizen because our 'leaders' can't say no!", "Sadly, because president Obama has done such a poor job as president, you won’t see another black president for generations!","And, you know, I have a great relationship with African Americans, as you possibly have heard. I just have great respect for them and you know they like me.","Black guys counting my money! I hate it. The only kind of people I want counting my money are short guys that wear yarmulkes every day.", "I have a great relationship with the blacks.", "Laziness is a trait in blacks"],
        :his_own_fame => ["I do not wear a rug. My hair is one hundred percent mine.","I don’t think Ivanka would do that, although she does have a very nice figure. I’ve said if Ivanka weren’t my daughter, perhaps I’d be dating her.","The only kind of people I want counting my money are little short guys that wear yamakas every day.","My twitter has become so powerful that I can actually make my enemies tell the truth.", "Sorry losers and haters, but my IQ is one of the highest—and you all know it! Please don’t feel so stupid or insecure, it’s not your fault.", "That's one of the nice things. I mean, part of the beauty of me is that I'm very rich. So if I need $600 million, I can put $600 million myself. That's a huge advantage. I must tell you, that's a huge advantage over the other candidates.", "The beauty of me is that I'm very rich.", "My fingers are long and beautiful, as, it has been well been documented, are various other parts of my body."],
    :Global_Warming => ["The concept of global warming was created by and for the Chinese in order to make U.S. manufacturing non-competitive.","It’s freezing and snowing in New York—we need global warming!", "This very expensive GLOBAL WARMING bullshit has got to stop. Our planet is freezing, record low temps, and our GW scientists are stuck in ice."],
    :Barack_Obama => ["Sadly, because president Obama has done such a poor job as president, you won’t see another black president for generations!","An 'extremely credible source' has called my office and told me that @BarackObama's birth certificate is a fraud."],
      :Gender => ["I just don’t feel good about it. I don’t feel right about it. And I take a lot of heat because I come from New York (Trump's thoughts on gay marriage)","Rosie O’Donnell’s disgusting both inside and out. You take a look at her, she’s a slob. She talks like a truck driver, she doesn’t have her facts, she’ll say anything that comes to her mind….I mean she’s basically a disaster.","She gets out there and she starts asking me all sorts of ridiculous questions, and you could see there was blood coming out of her eyes, blood coming out of her … wherever. (on Megyn Kelly during the Republican Presidential Debate)", "Love him or hate him, Trump is a man who is certain about what he wants and sets out to get it, no holds barred. Women find his power almost as much of a turn-on as his money.", "All of the women on The Apprentice flirted with me - consciously or unconsciously. That's to be expected." "You know, it doesn’t really matter what [the media] write as long as you’ve got a young and beautiful piece of ass.", "It's like in golf. A lot of people — I don't want this to sound trivial — but a lot of people are switching to these really long putters, very unattractive. It’s weird. You see these great players with these really long putters, because they can't sink three-footers anymore. And, I hate it. I am a traditionalist. I have so many fabulous friends who happen to be gay, but I am a traditionalist. (on gay marriage)", "For a man to be successful he needs support at home, just like my father had from my mother, not someone who is always griping and bitching."],
        :Celebrities => ["Do you mind if I sit back a little? Because your breath is very bad. (to Larry King)", "She's been with so many guys she makes me look like a baby, OK, with the other side. And, I just don't even find her attractive. That has nothing to do with why I said it though. (Trump on Angelina Jolie)", "I'd look her right in that fat, ugly face of hers and say, ‘Rosie, you’re fired.’ We’re all a little chubby, but Rosie’s just worse than most of us. But it’s not the chubbiness—Rosie is a very unattractive person, both inside and out."],
        :election_2016 => ["Some of the candidates, they went in and didn't know the air conditioner didn't work and sweated like dogs, and they didn't know the room was too big because they didn't have anybody there. How are they going to beat ISIS?", "I think the only difference between me and the other candidates is that I'm more honest and my women are more beautiful.", "#JebBush has to like the Mexican Illegals because of his wife", "If Hilary Clinton can't satisfy her husband, what makes her think she can satisfy America?", "I watch the speeches of these people, and they say the sun will rise, the moon will set, all sorts of wonderful things will happen, and people are saying, ‘What is going on? I just want a job"]
    }
      
      @quote = @quote_hash[@category.to_sym].sample
    end 
    
end 

   

  

